version: '3.8'
services:
  #Laravel Service
  app:
    container_name: laravel_base_docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel_base_docker
    volumes:
      - ./:/var/www/laravel_base_docker
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "8100:80"
      - "443:443"
    volumes:
      - .:/var/www/laravel_base_docker
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/laravel_base_docker
    depends_on:
      - app
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    tty: true
    ports:
      - "3334:3306"
    environment:
      MYSQL_DATABASE: laravel_base_docker
      MYSQL_USER: docker_user
      MYSQL_ROOT_PASSWORD: docker_root_password
      MYSQL_PASSWORD: docker_password
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
